apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ace-hpa
  namespace: PROD
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ace-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10

